export const routes_fakedata = [
  {
    id: "116631",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "delivered",
  },
  {
    id: "116632",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "on_road",
  },
  {
    id: "116633",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "delivered",
  },
  {
    id: "116634",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "on_road",
  },
  {
    id: "116635",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "on_road",
  },
  {
    id: "116636",
    routeName: "Ruta nombre",
    routeDetail: "34 paquetes",
    deliveredDate: "31 de Julio",
    mooverName: "Mauricio",
    status: "delivered",
  },
];
