export const packages_fakedata = [
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116630",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "confirmed",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116631",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "pending",
    destinatary: "Mauricio Guzman Madrigal",
  },
  {
    id: "116632",
    address: "Teatro Nacional de Costa Rica, 1, San José, Catedral, Costa Rica",
    status: "cancelled",
    destinatary: "Mauricio Guzman Madrigal",
  },
];
